package im.tox.tox4j.crypto;

public class ToxCryptoConstants {
    /**
     * Length of salt in bytes.
     */
    public static int SaltLength = 32;

    /**
     * The number of bytes in a serialised [[ToxCrypto.PassKey]] without salt.
     * The serialised size is [[KeyLength]] + [[SaltLength]].
     */
    public static int KeyLength = 32;

    /**
     * Number of bytes added to any encrypted data.
     */
    public static int EncryptionExtraLength = 80;

    /**
     * The number of bytes in a hash generated by tox_hash.
     */
    public static int HashLength = 32;

    public static int PublicKeyLength = 32;
    public static int SecretKeyLength = 32;
    public static int SharedKeyLength = 32;
    public static int NonceLength = 24;

    public static int ZeroBytes = 32;
    public static int BoxZeroBytes = 16;
}
